// GENERATED by scripts/seed_extraction_workbooks.py from
// docs/extraction workbooks (Extraction Protocol + Universal Rules tabs).
// This is the LOCKED Platform Core layer of the extraction prompt —
// not org-editable anywhere. Do not hand-edit; re-run the script.

export const EXTRACTION_PROTOCOL = \`EXTRACTION PROTOCOL (Platform Core — locked)

Step 1: Attribute every speaker before extracting anything
Build a speaker map first. Rep-side: the AE, SC, and any seller-side participant (identify from introductions, email domains in the invite context, and self-references like 'here at Sage'). Prospect-side: everyone else, mapped to name and title when stated. If a speaker cannot be confidently classified, treat them as rep-side for fact purposes: misclassifying a rep as a prospect creates false facts, misclassifying a prospect as a rep only loses a fact (recoverable). Record the speaker map in the output so attribution is auditable.

Step 2: Read the full transcript once before extracting any field
First pass is comprehension only: understand the company, who's who, what was discussed, and where corrections happened. Facts are frequently corrected or refined later in a call ('actually, it's twelve with the new one'). Extracting on first mention without the full-read pass produces stale values the call itself superseded.

Step 3: Locate answers in all four shapes they take
(a) Direct answer to a question. (b) Volunteered fact inside a story or aside; these are often the richest and easiest to miss ('...because all nine LLCs share one bookkeeper' answers entity_count and staffing in a subordinate clause). (c) Confirmed rep statement: rep states a fact, prospect explicitly confirms with content ('right, twelve', 'yes exactly'). (d) Correction: a later statement revising an earlier one. Scan for all four; do not extract only from Q&A pairs.

Step 4: Apply the confirmation standard strictly
A rep-stated fact becomes a prospect fact ONLY with explicit contentful confirmation: 'yes', 'right', 'exactly', 'that's correct', or restating the value. Filler acknowledgments ('mm-hm', 'sure', 'okay', 'I guess') while someone is talking are conversational lubricant, NOT confirmation; they produce partial status at most. When a confirmation creates the fact, the quote MUST include both the rep's statement and the prospect's confirmation so the evidence is honest about its shape.

Step 5: Select the minimal complete quote
The quote is the smallest contiguous span that contains the fact and makes it intelligible standalone. Include the preceding question when the answer is elliptical ('About twelve' means nothing without 'How many people would be in the system?'). Never stitch non-contiguous sentences into one quote; use multiple linked quotes instead. Never paraphrase inside quotation marks: the quote is verbatim or it is not a quote.

Step 6: Handle numbers with the containment rule
Every numeric value must appear in its quote, or be a flagged conversion from numbers in the quote (2 days/week -> ~800 hrs/yr, weekly -> monthly x4.33, 'parent plus nine' -> 10). Conversions are recorded as conversions with the arithmetic shown. Approximations keep their hedge ('call it 300, 350' -> 325, range noted). NEVER average two conflicting numbers, round a vague statement into a number ('a bunch of entities' is not a number), or import a number from another field's context.

Step 7: Preserve hedges; route hard uncertainty to partial
Soft hedges ('I think', 'probably', 'around') are extractable WITH the hedge preserved in the quote and noted: hedged facts are facts with stated confidence. Hard uncertainty ('I'd have to check', 'don't quote me', 'ask our controller') is partial status + a follow-up task with the named resolver. The line: did the speaker commit to a value, or defer? Deferral is never a value.

Step 8: Within one call, last statement wins; across calls, change-aware recency
Mid-call corrections supersede earlier statements; extract the corrected value and note the correction in the evidence. Across calls, classify against the prior value provided in context: new_fact (was Unknown), confirmation (same value restated; bump observed_at and reconfirmed counter), changed_fact (differs; new value wins, both values and sources recorded, qualifying-spine changes surface on the deal timeline).

Step 9: Multi-speaker conflict inside one call: capture both, decide nothing
If the CFO says nine entities and the controller says ten in the same call, write neither as the value. Record the conflict with both quotes, set partial, and generate a clarification task. Choosing between prospect-side speakers is inference; flagging the discrepancy is the finding.

Step 10: Negative findings are findings
'We don't use POs', 'no budget set', 'we've never counted inventory', 'there's no approval process' are answers, not absences. Write them as the value (false / none / not done) with the quote. The difference between not_discussed and a stated 'no' is exactly the gap analysis the SC and AE need.

Step 11: Route current vs desired before writing anything
Every field is current state unless its definition says otherwise. Aspirational markers ('we want', 'we'd love', 'ideally', 'we should', 'the goal is') route to ideal_solution / desired_reporting / success_definition. Past state ('we used to') is history color in notes, not the current value. One sentence can contain both ('close takes 18 days and we want it at 5'): split it, two routings, same quote linked to both.

Step 12: Disambiguate between adjacent fields using the anti-patterns
Before writing, check the field's negative signals: is this fact actually the neighbor's? The recurring confusions: billing timing vs revenue recognition; locations vs entities; pain vs catalyst vs compelling event; purchase approval vs bill approval; ideal-solution color vs must-have decision criteria; employee count vs user count; cost rates vs billing rates. When a statement genuinely answers two fields, link the quote to both; when it merely resembles the second field, the anti-pattern decides.

Step 13: Decide disposition: write, suggest, or skip
For each candidate: if the field is manual-locked -> suggest (field_suggestions row with full provenance), never write. If prior value exists from automated source -> write per change classification. If no quote/speaker support survives the gates above -> skip entirely; the model proposes nothing it cannot evidence. Pattern-level inferences (title implies role, industry implies pain) are neither written nor suggested as facts: they go to deal_hypotheses with reasoning and basis sources, or nowhere.

Step 14: Quantified problems link to pain
When an extracted value evidences a problem with stated cost, hours, or frequency, attach pain_link: match against existing deal_pain_points first (same underlying problem -> enrich with the new quote), otherwise propose a new pain row through the same quote gate. The dollar/hours quantification follows rule 6.

Step 15: Emit the structured contract and nothing else
Per field: status (found / partial / not_found / not_applicable), value, normalized_value, verbatim quote(s), speaker(s), change_classification, disposition, pain_link (optional), notes (conversions, hedges, conflicts). Per entity candidate: the entity contract plus match_against (existing row id or none). No prose, no commentary, no recommendations inside the extraction output: coaching lives in a different pass.

Step 16: Extract concepts, never question-answer pairs
The field catalog's question text documents what information is wanted; it is NOT a script and the rep will not ask those exact questions. A field is found whenever its canonical definition and signals match a prospect statement, regardless of what question (if any) preceded it: volunteered facts, asides, stories, and answers to differently-phrased questions all count equally. Never condition extraction on a question having been asked, and never down-rank a fact because it arrived unprompted; unprompted facts are often the most reliable.

Step 17: Run the metrics sweep on every transcript
After field extraction, make one dedicated pass capturing EVERY quantified business statement by a prospect-side speaker as a metric observation: value, unit, period (per month/year/event), as-of context, quote, speaker. Map to the metric taxonomy when the mapping is unambiguous (days to close -> close_days; 'customers pay us in about 60 days' -> dso); otherwise store under the prospect's own label, flagged unmapped for taxonomy review. The sweep is a safety net: a stated number that fits no field must still be captured. Field values and pain quantifications LINK to their metric observations (one fact, one home; the observation is the quantitative record). Containment rule 6 and speaker rule 4 apply in full.

UNIVERSAL RULES

- Quote gate: No value is written without a verbatim quote and speaker (transcript) or URL citation (research). No quote = field stays Unknown / not_discussed.
- Speaker discipline: Facts about the prospect's business require a prospect-side speaker stating or explicitly confirming. Rep-stated facts with silence or weak acknowledgment are partial at most.
- No hypothesis: Anything reasoned rather than stated goes to deal_hypotheses, never to fact fields. This includes title-based role inference and industry-pattern pains.
- Current vs desired: Every field is CURRENT STATE unless the definition says otherwise. Desires route to ideal_solution / desired_reporting / success_definition. Aspirational phrasing ('we want', 'we should', 'ideally') is the routing signal.
- Manual lock: Manually entered values are never overwritten by extraction. Contradicting evidence files a field_suggestions row with full provenance.
- Change-aware recency: Every write classifies as new_fact / confirmation / changed_fact against the prior value provided in context. changed_fact records both values and surfaces qualifying-spine changes on the deal timeline.
- One fact, one home: Each fact has one canonical storage home (see architecture doc field map). Quotes may link to multiple fields when one statement genuinely answers several, but the same fact never writes two homes.
- Partial + task: Ambiguous or incomplete answers write status=partial with the quote and generate a follow-up task. Partial never guesses the value.
- Numbers in quotes: A numeric value must appear in its quote or be a flagged unit conversion (weeks to business days, weekly to monthly). The edge function rejects numeric writes failing this containment check.
- Pain tie-in: Quantified functional answers that evidence a problem link to a deal_pain_points row (existing or proposed) via pain_point_id, subject to match-before-insert dedup.
- Gates: Section gate fields (inventory_type, project_types, uses_allocations) control whether the gated fields run. Gated-off fields are not_applicable, not not_discussed.
- Granola summaries: Granola AI summaries and notes are auxiliary context only. They can never serve as provenance; only the verbatim transcript produces quotes.
- Concept-driven, not question-anchored: The question text in this catalog documents INTENT; it is not a script. Reps ask similar-but-different questions and prospects volunteer facts unprompted. Extraction matches the canonical definition and signals against ANY phrasing, anywhere in the call: a fact buried in a story, an answer to a differently-worded question, or an aside all count equally. Never require that the catalog question (or any question) was asked.
- Metrics sweep: Independently of the field catalog, every quantified business statement by a prospect-side speaker is captured as a metric observation (value, unit, period, quote, speaker): stated metrics must never be lost because no field matched. Observations map to the metric taxonomy when unambiguous, otherwise store under the prospect's own label for review. Field values and pain quantifications link to their metric observations rather than duplicating them.
`;
