# Seeds the extraction-overhaul reference data from the docs/extraction
# workbooks (via the parsed JSON dumps). Generates idempotent SQL files in
# scripts/generated/ which are applied as Supabase migrations:
#
#   seed_field_definitions.sql  -> custom_field_definitions (platform template,
#                                  org_id NULL), 94 catalog fields with
#                                  payment_methods merged into
#                                  vendor_payment_methods (93 rows)
#   seed_core_entities.sql      -> extraction_definitions (8 entities, scope
#                                  'platform', org_id NULL)
#   seed_metric_taxonomy.sql    -> metric_taxonomy (22 rows)
#   seed_risk_definitions.sql   -> risk_definitions (27 rows)
#   seed_module_reference.sql   -> module_reference (starter list, SKUs mapped
#                                  by name-match against products separately)
#
# Idempotency: every INSERT is ON CONFLICT ... DO UPDATE, so re-running the
# generated SQL converges to the workbook state.
#
# The Universal Rules + Extraction Protocol tabs are emitted as
# supabase/functions/_shared/extraction-protocol.ts (locked Platform Core
# prompt segment).
import json, os, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PARSED = os.path.join(ROOT, 'docs', 'extraction', 'parsed')
OUT = os.path.join(ROOT, 'scripts', 'generated')
os.makedirs(OUT, exist_ok=True)

def load(name):
    return json.load(open(os.path.join(PARSED, name), encoding='utf-8'))

def q(s):
    # SQL string literal with single-quote doubling; None -> NULL
    if s is None or s == '':
        return 'NULL'
    return "'" + str(s).replace("'", "''") + "'"

def jarr(s):
    # Signals cells are newline- or semicolon-delimited phrasings -> jsonb array
    if not s:
        return "'[]'::jsonb"
    parts = [p.strip(' -•') for p in re.split(r'[\n;]+', str(s)) if p.strip(' -•')]
    return q(json.dumps(parts)) + '::jsonb'

sc_defs = load('sc_defs.json')
catalog = {r['Proposed field_key']: r for r in load('sc_catalog.json')['Field Catalog']}
ae = load('ae_defs.json')

# ── 1. custom_field_definitions (platform template scope: org_id NULL) ──────
TYPE_MAP = {'number': 'number', 'text': 'text', 'boolean': 'boolean', 'list': 'multiselect'}
STORAGE_MAP = {
    'company_systems': 'company_systems',
    'existing AE extraction': None,  # resolved per-field below
}
AE_ROUTING = {
    'driver_for_new_erp': 'business_catalysts',
    'problems_to_solve': 'deal_pain_points',
    'success_definition': 'deal_analysis.ideal_solution',
    'ideal_solution': 'deal_analysis.ideal_solution',
}

rows = []
sort = 0
for r in sc_defs['Field Definitions']:
    key = r['field_key']
    if key == 'payment_methods':
        continue  # merged into vendor_payment_methods (one definition)
    cat = catalog.get(key, {})
    stored_in = cat.get('Stored In', 'deal attribute (new)')
    if stored_in == 'company_systems':
        storage_target = 'company_systems'
    elif stored_in == 'existing AE extraction':
        storage_target = AE_ROUTING.get(key)
    else:
        storage_target = None
    ftype = TYPE_MAP.get(cat.get('Value Type', 'text'), 'text')
    sort += 10
    instructions = (r.get('Type & Normalization') or '')
    good, bad = r.get('Good Example') or '', r.get('Bad Example') or ''
    if good:
        instructions += '\nGood example: ' + good
    if bad:
        instructions += '\nBad example: ' + bad
    extra = ''
    if key == 'vendor_payment_methods':
        extra = ' (merged with payment_methods: one definition covers vendor payment rails)'
    rows.append(
        "(NULL, 'deal', "
        + ', '.join([
            q(key),
            q(r['Question']),
            q(ftype),
            q((r['Canonical Definition'] or '')[:500]),   # admin_description (NOT NULL)
            q(r['Section']),
            q((r['Canonical Definition'] or '') + extra),
            q(instructions.strip()),
            jarr(r.get('Positive Signals')),
            jarr(r.get('Negative Signals / Anti-patterns')),
            q(storage_target),
            str(sort),
        ])
        + ', true)'
    )

sql = """-- Generated by scripts/seed_extraction_workbooks.py — do not hand-edit.
-- Platform-template SC field catalog (org_id NULL mirrors the coaches
-- template convention).
CREATE UNIQUE INDEX IF NOT EXISTS idx_cfd_template_field_key
  ON public.custom_field_definitions(entity_type, field_key) WHERE org_id IS NULL;
INSERT INTO public.custom_field_definitions
  (org_id, entity_type, field_key, field_label, field_type, admin_description,
   display_section, ai_context, extraction_instructions, extraction_signals,
   negative_signals, storage_target, sort_order, is_active)
VALUES
""" + ",\n".join(rows) + """
ON CONFLICT (entity_type, field_key) WHERE org_id IS NULL
DO UPDATE SET
  field_label = EXCLUDED.field_label,
  field_type = EXCLUDED.field_type,
  display_section = EXCLUDED.display_section,
  ai_context = EXCLUDED.ai_context,
  extraction_instructions = EXCLUDED.extraction_instructions,
  extraction_signals = EXCLUDED.extraction_signals,
  negative_signals = EXCLUDED.negative_signals,
  storage_target = EXCLUDED.storage_target,
  sort_order = EXCLUDED.sort_order,
  is_active = true;
"""
open(os.path.join(OUT, 'seed_field_definitions.sql'), 'w', encoding='utf-8').write(sql)
print(f"field definitions: {len(rows)} rows")

# ── 2. extraction_definitions (8 core entities, platform scope) ─────────────
ENTITY_TABLE = {}
rows = []
for r in sc_defs['Core Entities']:
    ent = r['Entity'].strip().lower().replace(' ', '_')
    rows.append(
    "("
    + ", ".join([
        q(ent), "'platform'", 'NULL', 'NULL',
        q(r['Canonical Definition']),
        jarr(r.get('Anti-patterns')),
        q(json.dumps({'row_rules': r.get('Row & Normalization Rules') or '', 'signals': r.get('Positive Signals') or ''})) + '::jsonb',
        jarr(r.get('Good Example')),
        jarr(r.get('Bad Example')),
        'true'])
    + ")")
sql = """-- Generated by scripts/seed_extraction_workbooks.py — do not hand-edit.
CREATE UNIQUE INDEX IF NOT EXISTS idx_ed_platform_entity
  ON public.extraction_definitions(entity_type) WHERE scope = 'platform' AND org_id IS NULL;
INSERT INTO public.extraction_definitions
  (entity_type, scope, org_id, coach_id, canonical_definition, anti_patterns, grammar, good_examples, bad_examples, active)
VALUES
""" + ",\n".join(rows) + """
ON CONFLICT (entity_type) WHERE scope = 'platform' AND org_id IS NULL
DO UPDATE SET
  canonical_definition = EXCLUDED.canonical_definition,
  anti_patterns = EXCLUDED.anti_patterns,
  grammar = EXCLUDED.grammar,
  good_examples = EXCLUDED.good_examples,
  bad_examples = EXCLUDED.bad_examples,
  active = true;
"""
open(os.path.join(OUT, 'seed_core_entities.sql'), 'w', encoding='utf-8').write(sql)
print(f"core entities: {len(rows)} rows")

# ── 3. metric_taxonomy ──────────────────────────────────────────────────────
rows = []
for r in ae['Key Metrics']:
    rows.append("(" + ", ".join([
        q(r['metric_key']), q(r['Metric']), q(r['Definition']),
        q(r.get('Unit & Normalization')), q(r.get('Signals')), q(r.get('Feeds / Links To')), 'true']) + ")")
sql = """-- Generated by scripts/seed_extraction_workbooks.py — do not hand-edit.
INSERT INTO public.metric_taxonomy (metric_key, name, definition, unit_normalization, signals, feeds_links, active)
VALUES
""" + ",\n".join(rows) + """
ON CONFLICT (metric_key) DO UPDATE SET
  name = EXCLUDED.name, definition = EXCLUDED.definition,
  unit_normalization = EXCLUDED.unit_normalization, signals = EXCLUDED.signals,
  feeds_links = EXCLUDED.feeds_links, active = true;
"""
open(os.path.join(OUT, 'seed_metric_taxonomy.sql'), 'w', encoding='utf-8').write(sql)
print(f"metric taxonomy: {len(rows)} rows")

# ── 4. risk_definitions ─────────────────────────────────────────────────────
rows = []
for r in ae['Deal Risk Taxonomy']:
    ev = r.get('Evidence Type & Signals (STATED = quote-backed; GAP = computable absence)') or ''
    types = []
    if re.search(r'\bSTATED\b', ev, re.I):
        types.append('stated')
    if re.search(r'\bGAP\b', ev, re.I):
        types.append('gap')
    if not types:
        types = ['stated']
    rows.append("(" + ", ".join([
        q(r['risk_key']), q(r['Plain-Language Name (UI)']), q(r.get('Methodology Anchor (internal only)')),
        q(r.get('Definition')), q(ev),
        "ARRAY[" + ",".join(q(t) for t in types) + "]::text[]",
        q(r.get('Severity Rubric')), q(r.get('Example')), 'true']) + ")")
sql = """-- Generated by scripts/seed_extraction_workbooks.py — do not hand-edit.
INSERT INTO public.risk_definitions (risk_key, plain_name, methodology_anchor, definition, evidence_signals, evidence_types, severity_rubric, example, active)
VALUES
""" + ",\n".join(rows) + """
ON CONFLICT (risk_key) DO UPDATE SET
  plain_name = EXCLUDED.plain_name, methodology_anchor = EXCLUDED.methodology_anchor,
  definition = EXCLUDED.definition, evidence_signals = EXCLUDED.evidence_signals,
  evidence_types = EXCLUDED.evidence_types, severity_rubric = EXCLUDED.severity_rubric,
  example = EXCLUDED.example, active = true;
"""
open(os.path.join(OUT, 'seed_risk_definitions.sql'), 'w', encoding='utf-8').write(sql)
print(f"risk definitions: {len(rows)} rows")

# ── 5. module_reference starter list ────────────────────────────────────────
MODULES = [
    ('core_financials', 'Core Financials', 'GL, AP, AR, Cash Management, Order Entry, Purchasing', None, 10),
    ('dimensions', 'Dimensions', 'Dimensional GL tagging and reporting', None, 20),
    ('multi_entity_consolidations', 'Multi-Entity & Consolidations', 'Multi-entity management with automated consolidations and eliminations',
     {'any': [{'field': 'entity_count', 'op': '>', 'value': 1}, {'field': 'currencies_in_play', 'op': 'multi'}]}, 30),
    ('inventory', 'Inventory', 'Inventory management',
     {'any': [{'field': 'inventory_type', 'op': 'in', 'value': ['buy_to_sell', 'manufacturing', 'mixed']}]}, 40),
    ('order_management', 'Order Management', 'Sales order processing and fulfillment',
     {'any': [{'field': 'inventory_type', 'op': 'in', 'value': ['buy_to_sell', 'manufacturing', 'mixed']}]}, 50),
    ('project_costing_billing', 'Project Costing & Billing', 'Project accounting, costing, and billing',
     {'any': [{'field': 'project_types', 'op': 'nonempty'}]}, 60),
    ('contract_revenue_management', 'Contracts & Revenue Management', 'Contract-based billing with ASC 606 revenue recognition',
     {'any': [{'field': 'revenue_recognition_method', 'op': 'in', 'value': ['ratable', 'poc']}]}, 70),
    ('dynamic_allocations', 'Dynamic Allocations', 'Automated multi-basis allocations',
     {'any': [{'field': 'uses_allocations', 'op': 'true'}]}, 80),
    ('fixed_assets', 'Fixed Assets', 'Fixed asset lifecycle and depreciation',
     {'any': [{'field': 'fixed_asset_count', 'op': '>', 'value': 0}]}, 90),
    ('time_expense', 'Time & Expense', 'Time tracking and expense management', None, 100),
    ('planning', 'Sage Intacct Planning', 'Budgeting, forecasting, and scenario planning',
     {'any': [{'field': 'budgeting_process', 'op': 'answered'}]}, 110),
    ('avalara_tax', 'AvaTax (Avalara)', 'Automated sales tax calculation and filing', None, 120),
    ('vendor_payment_services', 'Vendor Payment Services', 'Outsourced vendor payment execution', None, 130),
    ('dashboards_reporting', 'Dashboards & Reporting (ICRW)', 'Interactive custom report writer and dashboards', None, 140),
    ('lease_accounting', 'Lease Accounting', 'ASC 842 lease accounting', None, 150),
]
rows = []
for key, name, desc, rules, sort_o in MODULES:
    rows.append("(" + ", ".join([
        q(key), q(name), q(desc), "'{}'::text[]",
        (q(json.dumps(rules)) + '::jsonb') if rules else 'NULL',
        str(sort_o), 'true']) + ")")
sql = """-- Generated by scripts/seed_extraction_workbooks.py — do not hand-edit.
INSERT INTO public.module_reference (module_key, name, description, maps_to_skus, suggestion_rules, sort_order, active)
VALUES
""" + ",\n".join(rows) + """
ON CONFLICT (module_key) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description,
  suggestion_rules = EXCLUDED.suggestion_rules, sort_order = EXCLUDED.sort_order, active = true;
"""
open(os.path.join(OUT, 'seed_module_reference.sql'), 'w', encoding='utf-8').write(sql)
print(f"module reference: {len(rows)} rows")

# ── 6. extraction-protocol.ts (locked Platform Core prompt segment) ─────────
proto = ae['Extraction Protocol']
rules = sc_defs['Universal Rules']
lines = ["// GENERATED by scripts/seed_extraction_workbooks.py from",
         "// docs/extraction workbooks (Extraction Protocol + Universal Rules tabs).",
         "// This is the LOCKED Platform Core layer of the extraction prompt —",
         "// not org-editable anywhere. Do not hand-edit; re-run the script.",
         "",
         "export const EXTRACTION_PROTOCOL = `EXTRACTION PROTOCOL (Platform Core — locked)",
         ""]
for r in proto:
    step = r['Step']
    lines.append(f"Step {step}: {r['Rule']}")
    if r.get('Directions'):
        lines.append(r['Directions'])
    lines.append("")
lines.append("UNIVERSAL RULES")
lines.append("")
for r in rules:
    lines.append(f"- {r['Rule']}: {r['Statement']}")
body = "\n".join(lines)
body = body.replace('\\', '\\\\').replace('`', '\\`').replace('${', '\\${')
ts = body + "\n`;\n"
os.makedirs(os.path.join(ROOT, 'supabase', 'functions', '_shared'), exist_ok=True)
open(os.path.join(ROOT, 'supabase', 'functions', '_shared', 'extraction-protocol.ts'), 'w', encoding='utf-8').write(ts)
print(f"extraction-protocol.ts: {len(proto)} steps + {len(rules)} rules")
